=== haniebayati/SpringCourse-exercise1/student.dtd
<!ELEMENT student (id,firstName,lastName,age,gender,address,contact,enrollment)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT address (street,city,zipCode)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT contact (email,phone)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT enrollment (year,major)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT major (#PCDATA)>

=== haniebayati/SpringCourse-exercise1/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
	<id>12345</id>
	<firstName>mohammad</firstName>
	<lastName>mohammadi</lastName>
	<age>17</age>
	<gender>male</gender>
	<address>
		<street>mirdamad street</street>
		<city>tehran</city>
		<zipCode>123456789</zipCode>
	</address>
	<contact>
		<email>mo.mohammadi@gmail.com</email>
		<phone>09123456789</phone>
	</contact>
	<enrollment>
		<year>2024</year>
		<major>computer</major>
	</enrollment>
</student>
